# Generated by Django 5.2.7 on 2025-10-07 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description for this token', max_length=100)),
                ('token', models.CharField(help_text='Slack access token', max_length=200)),
                ('team_name', models.CharField(blank=True, help_text='Team name from auth test', max_length=100)),
                ('user_name', models.CharField(blank=True, help_text='User name from auth test', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Slack channel ID', max_length=20)),
                ('channel_name', models.CharField(help_text='Slack channel name', max_length=100)),
                ('message_ts', models.CharField(help_text='Slack message timestamp', max_length=20, unique=True)),
                ('text', models.TextField(help_text='Message text content')),
                ('thread_ts', models.CharField(blank=True, help_text='Parent thread timestamp if this is a reply', max_length=20, null=True)),
                ('user_id', models.CharField(help_text='User ID who sent the message', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_id'], name='django_app__channel_8ced9a_idx'), models.Index(fields=['thread_ts'], name='django_app__thread__41807e_idx')],
            },
        ),
    ]
