# Generated by Django 5.2.7 on 2025-10-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slackmessage',
            name='django_app__thread__41807e_idx',
        ),
        migrations.RemoveField(
            model_name='slackmessage',
            name='thread_ts',
        ),
    ]
