# Generated by Django 5.2.7 on 2025-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_remove_slackmessage_django_app__thread__41807e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessage',
            name='is_thread_reply',
            field=models.BooleanField(default=False, help_text='Whether this message is a thread reply'),
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='thread_ts',
            field=models.CharField(blank=True, help_text='Thread timestamp if this is a reply', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='slackmessage',
            index=models.Index(fields=['thread_ts'], name='django_app__thread__41807e_idx'),
        ),
    ]
